id: AbstractConfig.startOnBoot
kind: property
ts_type: boolean
optional: true
description: |-
  [Android only] Set `true` to resume background-fetch events when the device is
  rebooted.  Defaults to `false`.

  ❗ NOTE: Requires [[AbstractConfig.stopOnTerminate]] `false`.
signatures:
  ts: "startOnBoot?: boolean;"
  dart: "bool? startOnBoot"
