id: AbstractConfig.enableHeadless
kind: property
ts_type: boolean
optional: true
description: |-
  [Android only] Set `true` to enable the [[BackgroundFetch.registerHeadlessTask]]
  mechanism for handling fetch events after app termination.  Defaults to `false`.

  !!! note
      Requires [[AbstractConfig.stopOnTerminate]] `false`.
platform_description:
  react-native: |-
    [Android only] Set `true` to enable React Native's [HeadlessJS](https://reactnative.dev/docs/headless-js-android)
    mechanism for handling fetch events after app termination.  Defaults to `false`.

    !!! note
        Requires [[AbstractConfig.stopOnTerminate]] `false`.

    📂 **`index.js`** (**MUST** be in `index.js`):

    ```typescript
    import BackgroundFetch from "react-native-background-fetch";

    const MyHeadlessTask = async (event) => {
      let taskId = event.taskId;
      let isTimeout = event.timeout;
      if (isTimeout) {
        // This task has exceeded its allowed running-time.
        console.log('[BackgroundFetch] Headless TIMEOUT:', taskId);
        BackgroundFetch.finish(taskId);
        return;
      }
      console.log('[BackgroundFetch HeadlessTask] start:', taskId);

      // Perform your work here...

      BackgroundFetch.finish(taskId);
    };

    // Register your BackgroundFetch HeadlessTask
    BackgroundFetch.registerHeadlessTask(MyHeadlessTask);
    ```
  capacitor: |-
    [Android only] Set `true` to enable the headless mechanism for handling fetch events
    after app termination.  Defaults to `false`.

    !!! note
        Requires [[AbstractConfig.stopOnTerminate]] `false`.

    ### Headless Setup

    With your app open in **Android Studio**, browse the **`app`** folder to find the **`MainActivity`** class.
    Right-click the *containing folder* and click **New > Java Class**.

    ![](https://dl.dropbox.com/s/ao511vydybru03y/capacitor-background-fetch-headless-setup-step1.png?dl=1)

    You **MUST** name the file **`BackgroundFetchHeadlessTask`**.

    ![](https://dl.dropbox.com/s/h15plzjh8mcsbur/capacitor-background-fetch-headless-setup-step2.png?dl=1)

    Add the following Java code, taking care to preserve your **`package`** declaration:

    ```java
    package com.your.package.name;  // <-- DO NOT REPLACE THIS LINE

    import android.content.Context;
    import android.util.Log;

    import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
    import com.transistorsoft.tsbackgroundfetch.BGTask;

    public class BackgroundFetchHeadlessTask {
        public void onFetch(Context context, BGTask task) {
            BackgroundFetch backgroundFetch = BackgroundFetch.getInstance(context);
            String taskId = task.getTaskId();
            boolean isTimeout = task.getTimedOut();
            if (isTimeout) {
                backgroundFetch.finish(taskId);
                return;
            }
            Log.d("MyHeadlessTask", "onFetch: " + taskId);
            // Do your work here...

            backgroundFetch.finish(taskId);
        }
    }
    ```

    ### Testing Your Headless Task

    After terminating your app, simulate a fetch event while observing **`$ adb logcat`**:

    ```bash
    adb shell cmd jobscheduler run -f com.your.app.package.name 999
    ```
  cordova: |-
    [Android only] Set `true` to enable the headless mechanism for handling fetch events
    after app termination.  Defaults to `false`.

    !!! note
        Requires [[AbstractConfig.stopOnTerminate]] `false`.

    !!! warning
        You must be prepared to **write Java code**.

    ### Headless Setup

    **Step 1:** Create a file named **`BackgroundFetchHeadlessTask.java`** in your app (e.g. `src/android/`).
    The file can be located anywhere but **MUST** be named **`BackgroundFetchHeadlessTask.java`**:

    ```java
    package com.transistorsoft.cordova.backgroundfetch;

    import android.content.Context;
    import android.util.Log;

    import com.transistorsoft.tsbackgroundfetch.BackgroundFetch;
    import com.transistorsoft.tsbackgroundfetch.BGTask;

    public class BackgroundFetchHeadlessTask implements HeadlessTask {
        @Override
        public void onFetch(Context context, BGTask task) {
            String taskId = task.getTaskId();
            boolean isTimeout = task.getTimedOut();
            if (isTimeout) {
                Log.d(BackgroundFetch.TAG, "TIMEOUT: " + taskId);
                BackgroundFetch.getInstance(context).finish(taskId);
                return;
            }
            Log.d(BackgroundFetch.TAG, "onFetch: " + taskId);
            // Perform your work here...

            BackgroundFetch.getInstance(context).finish(taskId);
        }
    }
    ```

    **Step 2:** In your **`config.xml`**, add a **`<resource-file>`** within `<platform name="android">`:

    ```xml
    <platform name="android">
        <resource-file
            src="src/android/BackgroundFetchHeadlessTask.java"
            target="app/src/main/java/com/transistorsoft/cordova/backgroundfetch/BackgroundFetchHeadlessTask.java" />
    </platform>
    ```

    - `src`: path to your custom `BackgroundFetchHeadlessTask.java`.
    - `target`: **must** be exactly as shown above.

    ### Testing Your Headless Task

    After terminating your app, simulate a fetch event while observing **`$ adb logcat`**:

    ```bash
    adb shell cmd jobscheduler run -f com.your.app.package.name 999
    ```
  flutter: |-
    [Android only] Set `true` to enable the headless mechanism for handling fetch events
    after app termination.  Defaults to `false`.

    !!! note
        Requires [[AbstractConfig.stopOnTerminate]] `false`.

    📂 **`lib/main.dart`**:

    ```dart
    import 'package:flutter/material.dart';
    import 'package:background_fetch/background_fetch.dart';

    // This "Headless Task" is run when the app is terminated.
    // Must be a top-level or static function.
    @pragma('vm:entry-point')
    void backgroundFetchHeadlessTask(HeadlessEvent task) async {
      String taskId = task.taskId;
      bool isTimeout = task.timeout;
      if (isTimeout) {
        // This task has exceeded its allowed running-time.
        print("[BackgroundFetch] Headless TIMEOUT: $taskId");
        BackgroundFetch.finish(taskId);
        return;
      }
      print("[BackgroundFetch] Headless event received: $taskId");
      BackgroundFetch.finish(taskId);
    }

    void main() {
      runApp(MyApp());

      // Register to receive BackgroundFetch events after app is terminated.
      // Requires {stopOnTerminate: false, enableHeadless: true}
      BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    }
    ```
signatures:
  ts: "enableHeadless?: boolean;"
  dart: "bool? enableHeadless"
